# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b0a5e313deebc1331f4ceb91926f3b9d28c8e293211940454e611f23d8916ef1ba94da4829a6a54fc3dbbc0c20e87853d197e0dcad400ca69a0c6d35357a85

test:
  secret_key_base: cdfaebd74778294966296970081fdb3083b7529968e7301847667acfd4f1ab051439e235f9675a7e2f84141c94ff16b8a6fd213192077f39f2747122974d521b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
